<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H3O127Q" ignored="10" name="Default test" tests="17" failures="6" timestamp="30 Aug 2019 12:06:55 GMT" time="234.773" errors="0">
  <testcase name="Verify_AdaptiveModel_For_Negative_Response" time="2.1" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Verify_AdaptiveModel_For_Negative_Response -->
  <testcase name="Verify_AdaptiveModel_For_Negative_Response" time="0.477" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Verify_AdaptiveModel_For_Negative_Response -->
  <testcase name="Verify_AdaptiveModel_For_Negative_Response" time="0.379" classname="regressionTests.RegressionCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regressionTests.RegressionCases.Verify_AdaptiveModel_For_Negative_Response(RegressionCases.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_AdaptiveModel_For_Negative_Response -->
  <testcase name="Verify_RealTimeEvent_API_Response_For_NewEvent" time="0.371" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Verify_RealTimeEvent_API_Response_For_NewEvent -->
  <testcase name="Verify_RealTimeEvent_API_Response_For_NewEvent" time="0.246" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Verify_RealTimeEvent_API_Response_For_NewEvent -->
  <testcase name="Verify_RealTimeEvent_API_Response_For_NewEvent" time="0.268" classname="regressionTests.RegressionCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regressionTests.RegressionCases.Verify_RealTimeEvent_API_Response_For_NewEvent(RegressionCases.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_RealTimeEvent_API_Response_For_NewEvent -->
  <testcase name="Verify_Discard_Version_Is_Successful" time="0.195" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Verify_Discard_Version_Is_Successful -->
  <testcase name="Verify_Discard_Version_Is_Successful" time="0.186" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Verify_Discard_Version_Is_Successful -->
  <testcase name="Verify_Discard_Version_Is_Successful" time="0.251" classname="regressionTests.RegressionCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regressionTests.RegressionCases.Verify_Discard_Version_Is_Successful(RegressionCases.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_Discard_Version_Is_Successful -->
  <testcase name="Verify_RealtimeSpine_Api" time="229.41" classname="regressionTests.RegressionCases"/>
  <testcase name="Ensure_Only_Expected_Channels_Are_Selected" time="0.113" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Ensure_Only_Expected_Channels_Are_Selected -->
  <testcase name="Ensure_Only_Expected_Channels_Are_Selected" time="0.087" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Ensure_Only_Expected_Channels_Are_Selected -->
  <testcase name="Ensure_Only_Expected_Channels_Are_Selected" time="0.086" classname="regressionTests.RegressionCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regressionTests.RegressionCases.Ensure_Only_Expected_Channels_Are_Selected(RegressionCases.java:167)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Ensure_Only_Expected_Channels_Are_Selected -->
  <testcase name="Ensure_PickBestChannel_Works_With_Channel_Heirarchy" time="0.093" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Ensure_PickBestChannel_Works_With_Channel_Heirarchy -->
  <testcase name="Ensure_PickBestChannel_Works_With_Channel_Heirarchy" time="0.12" classname="regressionTests.RegressionCases">
    <skipped/>
  </testcase> <!-- Ensure_PickBestChannel_Works_With_Channel_Heirarchy -->
  <testcase name="Ensure_PickBestChannel_Works_With_Channel_Heirarchy" time="0.095" classname="regressionTests.RegressionCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regressionTests.RegressionCases.Ensure_PickBestChannel_Works_With_Channel_Heirarchy(RegressionCases.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Ensure_PickBestChannel_Works_With_Channel_Heirarchy -->
  <testcase name="Verify_NewlyAdded_Subchannel_Is_Present_In_the_DataType" time="0.102" classname="regressionTests.RegressionCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at regressionTests.RegressionCases.Verify_NewlyAdded_Subchannel_Is_Present_In_the_DataType(RegressionCases.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_NewlyAdded_Subchannel_Is_Present_In_the_DataType -->
  <testcase name="Verify_Deleted_Offer_Is_Not_Present_In_CSV" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_Deleted_Offer_Is_Not_Present_In_CSV -->
  <testcase name="Verify_NewProperty_Added_Is_Available_in_DB" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_NewProperty_Added_Is_Available_in_DB -->
  <testcase name="Verify_Rollback_Is_Working_As_Expected" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_Rollback_Is_Working_As_Expected -->
  <testcase name="Verify_Offer_Rename_Is_Successfull" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_Offer_Rename_Is_Successfull -->
  <testcase name="Verify_DownloadedCSV_For_New_version" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_DownloadedCSV_For_New_version -->
  <testcase name="Verify_Creating_NewMicrositeTemp_ByAdding_Existing_Attribute" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_Creating_NewMicrositeTemp_ByAdding_Existing_Attribute -->
  <testcase name="Verify_IH_Deleted_For_All" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_IH_Deleted_For_All -->
  <testcase name="Verify_NewProperty_Added_Is_Available_in_PegaClass" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_NewProperty_Added_Is_Available_in_PegaClass -->
  <testcase name="Verify_NewEmailTemp_ByCloning" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_NewEmailTemp_ByCloning -->
  <testcase name="Verify_DownloadedCSV_For_Existing_Version" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_DownloadedCSV_For_Existing_Version -->
</testsuite> <!-- Default test -->
